POST http://localhost:5080/account/register
Content-Type: application/json

{
  "username": "Mona",
  "email": "mona@gmail.com",
  "password": "123456"
}
###

POST http://localhost:5080/account/login
Content-Type: application/json

{
  "email": "mona@gmail.com",
  "password": "123456"
}

###

GET http://localhost:5080/task/tasks?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcyMTA2ODI4NH0.x7c2kbzruS2pf1XbyFP6aZtxyXLYCSZZjOXq8Vq-qBSAzrNaNMioD-iYLdutLrSOL_x9j8i0m5TyruNXQcbr0A


###
PUT http://localhost:5080/task/changeStatus/3/InProgress
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcyMTA3MDM5NX0.sSHBVBYE6oA-YiPioI2mRrukBtM1Ns6aIRZ8BMv1NNMErni71mAFxaxt38mb1-XE6dbNMrbipP6O9Gkbep42cA

###
GET http://localhost:5080/task/count
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcyMTA2OTA0NH0.nr8w-obBeTqUJyNH_s6p84jnhG9p8QuFzp9CiTthxhHSF0A0Q2_t66ZuUilZBbZ3JUMBRajsZjLCac9Wuz-IEg

