POST http://localhost:5080/account/register
Content-Type: application/json

{
  "username": "Mona",
  "email": "mona@gmail.com",
  "password": "123456"
}
###

POST http://localhost:5080/account/login
Content-Type: application/json

{
  "email": "mona@gmail.com",
  "password": "123456"
}
